//
//  MultiAddScreenViewController.m
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import "MultiAddScreenViewController.h"
#import "WantViewController.h"
#import "ForSaleViewController.h"
#import "AreatradesViewController.h"
#import "MultiAddScreenWantViewController.h"

#import "GradientView.h"
#import "MKMapView+ZoomLevel.h"

@implementation MultiAddScreenViewController


- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation {
    return UIInterfaceOrientationIsPortrait(toInterfaceOrientation);
}

- (void)viewDidLoad {
  [super viewDidLoad];
  
  // ----------------------------;
  // View Controller Root View;
  // ----------------------------;
  
  self.view.backgroundColor = [UIColor colorWithPatternImage:[UIImage imageNamed:@"MultiAddScreenViewController_Image_1.png"]];
  UIView *contentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 460)];
  contentView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  
  // ----------------------------;
  // UITabBar -> tabBar1;
  // ----------------------------;
  
  UITabBar *tabBar1 = [[UITabBar alloc] initWithFrame:CGRectMake(0, 411, 320, 49)];
  tabBar1.tag = 1;
  tabBar1.delegate = (id<UITabBarDelegate>)self;
  [contentView addSubview:tabBar1];
  tabBar1.alpha = 1.0;
  tabBar1.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleTopMargin;
  [tabBar1 release];
  
  
  // ----------------------------;
  // Tab Bar Item -> tabBarItem1;
  // ----------------------------;
  
  UITabBarItem *tabBarItem1 = [[[UITabBarItem alloc] initWithTitle:@"Tradable" image:[UIImage imageNamed:@"MultiAddScreenViewController_Image_2.png"] tag:1] autorelease];
  
  
  // ----------------------------;
  // Tab Bar Item -> tabBarItem2;
  // ----------------------------;
  
  UITabBarItem *tabBarItem2 = [[[UITabBarItem alloc] initWithTitle:@"Want" image:[UIImage imageNamed:@"MultiAddScreenViewController_Image_3.png"] tag:2] autorelease];
  
  
  // ----------------------------;
  // Tab Bar Item -> tabBarItem3;
  // ----------------------------;
  
  UITabBarItem *tabBarItem3 = [[[UITabBarItem alloc] initWithTitle:@"For Sale" image:[UIImage imageNamed:@"MultiAddScreenViewController_Image_4.png"] tag:3] autorelease];
  
  
  // ----------------------------;
  // Tab Bar Item -> tabBarItem4;
  // ----------------------------;
  
  UITabBarItem *tabBarItem4 = [[[UITabBarItem alloc] initWithTitle:@"Area Trades" image:[UIImage imageNamed:@"MultiAddScreenViewController_Image_5.png"] tag:4] autorelease];
  
  tabBar1.items = [NSArray arrayWithObjects:tabBarItem1, tabBarItem2, tabBarItem3, tabBarItem4, nil];
  
  // ----------------------------;
  // MockTextureView -> textureView1;
  // ----------------------------;
  
  UIView *textureView1 = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 406)];
  UIView *textureView1ContentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 406)];
  textureView1ContentView.clipsToBounds = YES;
  textureView1ContentView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  [textureView1 addSubview:textureView1ContentView];
  [textureView1ContentView release];
  [contentView addSubview:textureView1];
  textureView1.alpha = 0.6470588445663452;
  textureView1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textureView1.backgroundColor = [UIColor colorWithRed:0.67 green:0.67 blue:0.67 alpha:1.0];
  textureView1.layer.cornerRadius = 2.0;
  textureView1.layer.borderWidth = 0.0;
  textureView1.layer.borderColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0].CGColor;
  textureView1.layer.shadowColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0].CGColor;
  textureView1.layer.shadowOpacity = 0.34117648005485535;
  textureView1.layer.shadowRadius = 5.0;
  textureView1ContentView.layer.cornerRadius = 2.0;
  textureView1.layer.shadowOffset = CGSizeMake(0, -3);
  [textureView1 release];
  
  
  // ----------------------------;
  // UINavigationBar -> navigationBar1;
  // ----------------------------;
  
  UINavigationBar *navigationBar1 = [[UINavigationBar alloc] initWithFrame:CGRectMake(0, 0, 320, 44)];
  navigationBar1.delegate = (id<UINavigationBarDelegate>)self;
  UINavigationItem *navigationBar1BackItem = [[[UINavigationItem alloc] initWithTitle:nil] autorelease];
  UINavigationItem *navigationBar1TopItem = [[[UINavigationItem alloc] initWithTitle:nil] autorelease];
  NSArray *navigationBar1Items = [NSArray arrayWithObjects:navigationBar1BackItem, navigationBar1TopItem, nil];
  [navigationBar1 setItems:navigationBar1Items animated:NO];
  [textureView1ContentView addSubview:navigationBar1];
  navigationBar1.alpha = 1.0;
  navigationBar1.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleBottomMargin;
  navigationBar1.barStyle = UIBarStyleDefault;
  navigationBar1.tintColor = [UIColor colorWithRed:0.2 green:0.2 blue:0.2 alpha:1.0];
  navigationBar1.topItem.title = @"Swapmedia";
  [navigationBar1 setTitleVerticalPositionAdjustment:0.0 forBarMetrics:UIBarMetricsDefault];
  navigationBar1.topItem.hidesBackButton = YES;
  [navigationBar1 release];
  
  
  // ----------------------------;
  // UIButton -> lightInfoButton1;
  // ----------------------------;
  
  UIButton *lightInfoButton1 = [UIButton buttonWithType:UIButtonTypeInfoLight];
  CGRect lightInfoButton1Rect = lightInfoButton1.frame;
  lightInfoButton1Rect.origin.x = 17;
  lightInfoButton1Rect.origin.y =  10;
  lightInfoButton1.frame = lightInfoButton1Rect;
  [textureView1ContentView addSubview:lightInfoButton1];
  lightInfoButton1.alpha = 1.0;
  lightInfoButton1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  
  
  // ----------------------------;
  // UIButton -> roundedRectButton2;
  // ----------------------------;
  
  UIButton *roundedRectButton2 = [UIButton buttonWithType:UIButtonTypeRoundedRect];
  roundedRectButton2.frame = CGRectMake(244, 0, 72, 29);
  [textureView1ContentView addSubview:roundedRectButton2];
  roundedRectButton2.alpha = 1.0;
  roundedRectButton2.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [roundedRectButton2 setTitle:@"Cancel" forState:UIControlStateNormal];
  [roundedRectButton2 setTitleColor:[UIColor colorWithRed:0.22 green:0.33 blue:0.53 alpha:1.0] forState:UIControlStateNormal];
  roundedRectButton2.titleLabel.font = [UIFont fontWithName:@".HelveticaNeueUI-Bold" size:15.0];
  [roundedRectButton2 addTarget:self action:@selector(didTap_roundedRectButton2:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // UIButton -> imageButton3;
  // ----------------------------;
  
  UIButton *imageButton3 = [UIButton buttonWithType:UIButtonTypeCustom];
  imageButton3.frame = CGRectMake(0, 112, 320, 55);
  [textureView1ContentView addSubview:imageButton3];
  imageButton3.alpha = 1.0;
  imageButton3.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [imageButton3 setTitle:@"Add Music" forState:UIControlStateNormal];
  [imageButton3 setImage:[UIImage imageNamed:@"MultiAddScreenViewController_Image_6.png"] forState:UIControlStateNormal];
  [imageButton3 setBackgroundImage:[UIImage imageNamed:@"MultiAddScreenViewController_Image_7.png"] forState:UIControlStateNormal];
  imageButton3.enabled = YES;
  [imageButton3 setTitleColor:[UIColor colorWithRed:0.0 green:0.25 blue:0.5 alpha:1.0] forState:UIControlStateNormal];
  [imageButton3 addTarget:self action:@selector(didTap_imageButton3:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // UIButton -> imageButton4;
  // ----------------------------;
  
  UIButton *imageButton4 = [UIButton buttonWithType:UIButtonTypeCustom];
  imageButton4.frame = CGRectMake(0, 49, 320, 55);
  [textureView1ContentView addSubview:imageButton4];
  imageButton4.alpha = 1.0;
  imageButton4.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [imageButton4 setTitle:@"Add Movie" forState:UIControlStateNormal];
  [imageButton4 setImage:[UIImage imageNamed:@"MultiAddScreenViewController_Image_8.png"] forState:UIControlStateNormal];
  [imageButton4 setBackgroundImage:[UIImage imageNamed:@"MultiAddScreenViewController_Image_9.png"] forState:UIControlStateNormal];
  imageButton4.enabled = YES;
  [imageButton4 setTitleColor:[UIColor colorWithRed:0.0 green:0.25 blue:0.5 alpha:1.0] forState:UIControlStateNormal];
  [imageButton4 addTarget:self action:@selector(didTap_imageButton4:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // UIButton -> imageButton5;
  // ----------------------------;
  
  UIButton *imageButton5 = [UIButton buttonWithType:UIButtonTypeCustom];
  imageButton5.frame = CGRectMake(0, 176, 320, 55);
  [textureView1ContentView addSubview:imageButton5];
  imageButton5.alpha = 1.0;
  imageButton5.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [imageButton5 setTitle:@"Add Games" forState:UIControlStateNormal];
  [imageButton5 setImage:[UIImage imageNamed:@"MultiAddScreenViewController_Image_10.png"] forState:UIControlStateNormal];
  [imageButton5 setBackgroundImage:[UIImage imageNamed:@"MultiAddScreenViewController_Image_11.png"] forState:UIControlStateNormal];
  imageButton5.enabled = YES;
  [imageButton5 setTitleColor:[UIColor colorWithRed:0.0 green:0.25 blue:0.5 alpha:1.0] forState:UIControlStateNormal];
  [imageButton5 addTarget:self action:@selector(didTap_imageButton5:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  contentView.frame = self.view.bounds;
  [self.view addSubview:contentView];
  [contentView release];
}

- (void)viewDidUnload {
  [super viewDidUnload];
}

- (void)dealloc {
  [super dealloc];
}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationFade];
    [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleDefault animated:animated];
}


// ----------------
// Tab Bar
// ----------------

- (void)tabBar:(UITabBar *)tabBar didSelectItem:(UITabBarItem *)item {
  if (tabBar.tag == 1 && item.tag == 2) {;
    [self didTap_tabBarItem2];
  };
  if (tabBar.tag == 1 && item.tag == 3) {;
    [self didTap_tabBarItem3];
  };
  if (tabBar.tag == 1 && item.tag == 4) {;
    [self didTap_tabBarItem4];
  };
}


// ----------------
// Navigation Bar
// ----------------

- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
  return NO;
}

// ----------------
// Action
// ----------------

- (void)didTap_tabBarItem2 {
  WantViewController *controller = [[WantViewController alloc] init];
  [self.navigationController pushViewController:controller animated:YES];
  [controller release];
}
- (void)didTap_tabBarItem3 {
  ForSaleViewController *controller = [[ForSaleViewController alloc] init];
  [self.navigationController pushViewController:controller animated:YES];
  [controller release];
}
- (void)didTap_tabBarItem4 {
  AreatradesViewController *controller = [[AreatradesViewController alloc] init];
  [self.navigationController pushViewController:controller animated:YES];
  [controller release];
}
- (void)didTap_roundedRectButton2:(id)sender forEvent:(UIEvent *)event {
  [self.navigationController popViewControllerAnimated:YES];
}
- (void)didTap_imageButton3:(id)sender forEvent:(UIEvent *)event {
  UIAlertView *alertView = [[UIAlertView alloc] init];
  alertView.title = @"Not enabled ";
  alertView.message = @"";
  [alertView addButtonWithTitle:@"OK"];
  [alertView show];
  [alertView release];
}
- (void)didTap_imageButton4:(id)sender forEvent:(UIEvent *)event {
  MultiAddScreenWantViewController *controller = [[MultiAddScreenWantViewController alloc] init];
  [self.navigationController pushViewController:controller animated:YES];
  [controller release];
}
- (void)didTap_imageButton5:(id)sender forEvent:(UIEvent *)event {
  UIAlertView *alertView = [[UIAlertView alloc] init];
  alertView.title = @"Not enabled";
  alertView.message = @"";
  [alertView addButtonWithTitle:@"OK"];
  [alertView show];
  [alertView release];
}




@end