//
//  MultiAddScreenWantViewController.h
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>

@interface MultiAddScreenWantViewController : UIViewController {
  
}

@property (nonatomic, retain) NSMutableArray *picker1Data;

@end