//
//  WantViewController.h
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>

@interface WantViewController : UIViewController {
  
}

@property (nonatomic, retain) NSMutableArray *tableView2Data;

@end