//
//  WantMenuViewController.m
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import "WantMenuViewController.h"
#import "TradeMenuViewController.h"
#import "ForSaleViewController.h"
#import "AreatradesViewController.h"
#import "InfoViewController.h"
#import "WantViewController.h"
#import "MultiAddScreenViewController.h"

#import "GradientView.h"
#import "MKMapView+ZoomLevel.h"

@implementation WantMenuViewController


- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation {
    return UIInterfaceOrientationIsPortrait(toInterfaceOrientation);
}

- (void)viewDidLoad {
  [super viewDidLoad];
  
  // ----------------------------;
  // View Controller Root View;
  // ----------------------------;
  
  self.view.backgroundColor = [UIColor colorWithPatternImage:[UIImage imageNamed:@"WantMenuViewController_Image_1.png"]];
  UIView *contentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 460)];
  contentView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  
  // ----------------------------;
  // UITabBar -> tabBar1;
  // ----------------------------;
  
  UITabBar *tabBar1 = [[UITabBar alloc] initWithFrame:CGRectMake(0, 411, 320, 49)];
  tabBar1.tag = 1;
  tabBar1.delegate = (id<UITabBarDelegate>)self;
  [contentView addSubview:tabBar1];
  tabBar1.alpha = 1.0;
  tabBar1.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleTopMargin;
  [tabBar1 release];
  
  
  // ----------------------------;
  // Tab Bar Item -> tabBarItem1;
  // ----------------------------;
  
  UITabBarItem *tabBarItem1 = [[[UITabBarItem alloc] initWithTitle:@"Tradable" image:[UIImage imageNamed:@"WantMenuViewController_Image_2.png"] tag:1] autorelease];
  
  
  // ----------------------------;
  // Tab Bar Item -> tabBarItem2;
  // ----------------------------;
  
  UITabBarItem *tabBarItem2 = [[[UITabBarItem alloc] initWithTitle:@"Want" image:[UIImage imageNamed:@"WantMenuViewController_Image_3.png"] tag:2] autorelease];
  tabBarItem2.badgeValue = @"3";
  
  
  // ----------------------------;
  // Tab Bar Item -> tabBarItem3;
  // ----------------------------;
  
  UITabBarItem *tabBarItem3 = [[[UITabBarItem alloc] initWithTitle:@"For Sale" image:[UIImage imageNamed:@"WantMenuViewController_Image_4.png"] tag:3] autorelease];
  
  
  // ----------------------------;
  // Tab Bar Item -> tabBarItem4;
  // ----------------------------;
  
  UITabBarItem *tabBarItem4 = [[[UITabBarItem alloc] initWithTitle:@"Area Trades" image:[UIImage imageNamed:@"WantMenuViewController_Image_5.png"] tag:4] autorelease];
  
  tabBar1.items = [NSArray arrayWithObjects:tabBarItem1, tabBarItem2, tabBarItem3, tabBarItem4, nil];
  
  // ----------------------------;
  // MockTextureView -> textureView1;
  // ----------------------------;
  
  UIView *textureView1 = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 410)];
  UIView *textureView1ContentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 410)];
  textureView1ContentView.clipsToBounds = YES;
  textureView1ContentView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  [textureView1 addSubview:textureView1ContentView];
  [textureView1ContentView release];
  [contentView addSubview:textureView1];
  textureView1.alpha = 0.6235294342041016;
  textureView1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  textureView1.backgroundColor = [UIColor colorWithRed:0.67 green:0.67 blue:0.67 alpha:1.0];
  textureView1.layer.cornerRadius = 2.0;
  textureView1.layer.borderWidth = 0.0;
  textureView1.layer.borderColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0].CGColor;
  textureView1.layer.shadowColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0].CGColor;
  textureView1.layer.shadowOpacity = 0.34117648005485535;
  textureView1.layer.shadowRadius = 5.0;
  textureView1ContentView.layer.cornerRadius = 2.0;
  textureView1.layer.shadowOffset = CGSizeMake(0, -3);
  textureView1ContentView.backgroundColor = [UIColor colorWithPatternImage:[UIImage imageNamed:@"WantMenuViewController_Image_6.png"]];
  [textureView1 release];
  
  
  // ----------------------------;
  // UINavigationBar -> navigationBar1;
  // ----------------------------;
  
  UINavigationBar *navigationBar1 = [[UINavigationBar alloc] initWithFrame:CGRectMake(0, 0, 320, 44)];
  navigationBar1.delegate = (id<UINavigationBarDelegate>)self;
  UINavigationItem *navigationBar1BackItem = [[[UINavigationItem alloc] initWithTitle:nil] autorelease];
  UINavigationItem *navigationBar1TopItem = [[[UINavigationItem alloc] initWithTitle:nil] autorelease];
  NSArray *navigationBar1Items = [NSArray arrayWithObjects:navigationBar1BackItem, navigationBar1TopItem, nil];
  [navigationBar1 setItems:navigationBar1Items animated:NO];
  [textureView1ContentView addSubview:navigationBar1];
  navigationBar1.alpha = 1.0;
  navigationBar1.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleBottomMargin;
  navigationBar1.barStyle = UIBarStyleDefault;
  navigationBar1.tintColor = [UIColor colorWithRed:0.0 green:0.25 blue:0.5 alpha:1.0];
  navigationBar1.topItem.title = @"Want Menu";
  [navigationBar1 setTitleVerticalPositionAdjustment:0.0 forBarMetrics:UIBarMetricsDefault];
  navigationBar1.topItem.hidesBackButton = YES;
  
  // ----------------------------;
  // Navigation Bar Right Button -> barButton1;
  // ----------------------------;
  
  UIBarButtonItem *barButton1 = [[[UIBarButtonItem alloc] initWithImage:[UIImage imageNamed:@"WantMenuViewController_Image_7.png"] style:UIBarButtonItemStyleBordered target:nil action:nil] autorelease];
  [barButton1 setTintColor:[UIColor colorWithRed:1.0 green:1.0 blue:0.4 alpha:1.0]];
  barButton1.target = self;
  barButton1.action = @selector(didTap_barButton1:forEvent:);
  
  navigationBar1.topItem.rightBarButtonItem = barButton1;
  [navigationBar1 release];
  
  
  // ----------------------------;
  // UIButton -> lightInfoButton1;
  // ----------------------------;
  
  UIButton *lightInfoButton1 = [UIButton buttonWithType:UIButtonTypeInfoLight];
  CGRect lightInfoButton1Rect = lightInfoButton1.frame;
  lightInfoButton1Rect.origin.x = 17;
  lightInfoButton1Rect.origin.y =  10;
  lightInfoButton1.frame = lightInfoButton1Rect;
  [textureView1ContentView addSubview:lightInfoButton1];
  lightInfoButton1.alpha = 1.0;
  lightInfoButton1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [lightInfoButton1 addTarget:self action:@selector(didTap_lightInfoButton1:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // UILabel -> label1;
  // ----------------------------;
  
  UILabel *label1 = [[UILabel alloc] initWithFrame:CGRectMake(24, 115, 78, 25)];
  [textureView1ContentView addSubview:label1];
  label1.alpha = 1.0;
  label1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label1.text = @"Pre-order";
  label1.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label1.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label1.textAlignment = UITextAlignmentCenter;
  label1.shadowOffset = CGSizeMake(0, -1);
  label1.font = [UIFont fontWithName:@"ArialMT" size:12.0];
  [label1 release];
  
  
  // ----------------------------;
  // UILabel -> label2;
  // ----------------------------;
  
  UILabel *label2 = [[UILabel alloc] initWithFrame:CGRectMake(128, 115, 78, 25)];
  [textureView1ContentView addSubview:label2];
  label2.alpha = 1.0;
  label2.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label2.text = @"Social Post";
  label2.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label2.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label2.textAlignment = UITextAlignmentCenter;
  label2.shadowOffset = CGSizeMake(0, -1);
  label2.font = [UIFont fontWithName:@"ArialMT" size:12.0];
  [label2 release];
  
  
  // ----------------------------;
  // UILabel -> label3;
  // ----------------------------;
  
  UILabel *label3 = [[UILabel alloc] initWithFrame:CGRectMake(226, 115, 78, 25)];
  [textureView1ContentView addSubview:label3];
  label3.alpha = 1.0;
  label3.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label3.text = @"Want List";
  label3.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label3.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label3.textAlignment = UITextAlignmentCenter;
  label3.shadowOffset = CGSizeMake(0, -1);
  label3.font = [UIFont fontWithName:@"ArialMT" size:12.0];
  [label3 release];
  
  
  // ----------------------------;
  // UILabel -> label4;
  // ----------------------------;
  
  UILabel *label4 = [[UILabel alloc] initWithFrame:CGRectMake(18, 227, 91, 37)];
  [textureView1ContentView addSubview:label4];
  label4.alpha = 1.0;
  label4.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label4.text = @"Current Demand";
  label4.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label4.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label4.textAlignment = UITextAlignmentCenter;
  label4.shadowOffset = CGSizeMake(0, -1);
  label4.font = [UIFont fontWithName:@"ArialMT" size:12.0];
  [label4 release];
  
  
  // ----------------------------;
  // UILabel -> label5;
  // ----------------------------;
  
  UILabel *label5 = [[UILabel alloc] initWithFrame:CGRectMake(121, 227, 91, 37)];
  [textureView1ContentView addSubview:label5];
  label5.alpha = 1.0;
  label5.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label5.text = @"Wanted Media";
  label5.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label5.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label5.textAlignment = UITextAlignmentCenter;
  label5.shadowOffset = CGSizeMake(0, -1);
  label5.font = [UIFont fontWithName:@"ArialMT" size:12.0];
  [label5 release];
  
  
  // ----------------------------;
  // UILabel -> label6;
  // ----------------------------;
  
  UILabel *label6 = [[UILabel alloc] initWithFrame:CGRectMake(226, 227, 91, 37)];
  [textureView1ContentView addSubview:label6];
  label6.alpha = 1.0;
  label6.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label6.text = @"Release Dates";
  label6.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label6.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label6.textAlignment = UITextAlignmentCenter;
  label6.shadowOffset = CGSizeMake(0, -1);
  label6.font = [UIFont fontWithName:@"ArialMT" size:12.0];
  [label6 release];
  
  
  // ----------------------------;
  // UILabel -> label7;
  // ----------------------------;
  
  UILabel *label7 = [[UILabel alloc] initWithFrame:CGRectMake(19, 344, 91, 37)];
  [textureView1ContentView addSubview:label7];
  label7.alpha = 1.0;
  label7.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label7.text = @"Rip off traders";
  label7.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label7.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label7.textAlignment = UITextAlignmentCenter;
  label7.shadowOffset = CGSizeMake(0, -1);
  label7.font = [UIFont fontWithName:@"ArialMT" size:12.0];
  [label7 release];
  
  
  // ----------------------------;
  // UIImageView -> imageView1;
  // ----------------------------;
  
  UIImageView *imageView1 = [[UIImageView alloc] initWithFrame:CGRectMake(51, 371, 218, 31)];
  [textureView1ContentView addSubview:imageView1];
  imageView1.alpha = 1.0;
  imageView1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  imageView1.image = [UIImage imageNamed:@"WantMenuViewController_Image_8.png"];
  imageView1.contentMode = UIViewContentModeScaleToFill;
  [imageView1 release];
  
  
  // ----------------------------;
  // UIButton -> imageButton2;
  // ----------------------------;
  
  UIButton *imageButton2 = [UIButton buttonWithType:UIButtonTypeCustom];
  imageButton2.frame = CGRectMake(238, 61, 53, 54);
  [textureView1ContentView addSubview:imageButton2];
  imageButton2.alpha = 1.0;
  imageButton2.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [imageButton2 setTitle:@"" forState:UIControlStateNormal];
  [imageButton2 setImage:[UIImage imageNamed:@"WantMenuViewController_Image_9.png"] forState:UIControlStateNormal];
  imageButton2.enabled = YES;
  [imageButton2 setTitleColor:[UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0] forState:UIControlStateNormal];
  [imageButton2 addTarget:self action:@selector(didTap_imageButton2:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // UIButton -> imageButton3;
  // ----------------------------;
  
  UIButton *imageButton3 = [UIButton buttonWithType:UIButtonTypeCustom];
  imageButton3.frame = CGRectMake(141, 61, 53, 54);
  [textureView1ContentView addSubview:imageButton3];
  imageButton3.alpha = 1.0;
  imageButton3.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [imageButton3 setTitle:@"" forState:UIControlStateNormal];
  [imageButton3 setImage:[UIImage imageNamed:@"WantMenuViewController_Image_10.png"] forState:UIControlStateNormal];
  imageButton3.enabled = YES;
  [imageButton3 setTitleColor:[UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0] forState:UIControlStateNormal];
  [imageButton3 addTarget:self action:@selector(didTap_imageButton3:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // UIButton -> imageButton4;
  // ----------------------------;
  
  UIButton *imageButton4 = [UIButton buttonWithType:UIButtonTypeCustom];
  imageButton4.frame = CGRectMake(37, 61, 53, 54);
  [textureView1ContentView addSubview:imageButton4];
  imageButton4.alpha = 1.0;
  imageButton4.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [imageButton4 setTitle:@"" forState:UIControlStateNormal];
  [imageButton4 setImage:[UIImage imageNamed:@"WantMenuViewController_Image_11.png"] forState:UIControlStateNormal];
  imageButton4.enabled = YES;
  [imageButton4 setTitleColor:[UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0] forState:UIControlStateNormal];
  [imageButton4 addTarget:self action:@selector(didTap_imageButton4:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // UIButton -> imageButton5;
  // ----------------------------;
  
  UIButton *imageButton5 = [UIButton buttonWithType:UIButtonTypeCustom];
  imageButton5.frame = CGRectMake(37, 166, 53, 54);
  [textureView1ContentView addSubview:imageButton5];
  imageButton5.alpha = 1.0;
  imageButton5.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [imageButton5 setTitle:@"" forState:UIControlStateNormal];
  [imageButton5 setImage:[UIImage imageNamed:@"WantMenuViewController_Image_12.png"] forState:UIControlStateNormal];
  imageButton5.enabled = YES;
  [imageButton5 setTitleColor:[UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0] forState:UIControlStateNormal];
  [imageButton5 addTarget:self action:@selector(didTap_imageButton5:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // UIButton -> imageButton6;
  // ----------------------------;
  
  UIButton *imageButton6 = [UIButton buttonWithType:UIButtonTypeCustom];
  imageButton6.frame = CGRectMake(141, 166, 53, 54);
  [textureView1ContentView addSubview:imageButton6];
  imageButton6.alpha = 1.0;
  imageButton6.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [imageButton6 setTitle:@"" forState:UIControlStateNormal];
  [imageButton6 setImage:[UIImage imageNamed:@"WantMenuViewController_Image_13.png"] forState:UIControlStateNormal];
  imageButton6.enabled = YES;
  [imageButton6 setTitleColor:[UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0] forState:UIControlStateNormal];
  [imageButton6 addTarget:self action:@selector(didTap_imageButton6:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // UIButton -> imageButton7;
  // ----------------------------;
  
  UIButton *imageButton7 = [UIButton buttonWithType:UIButtonTypeCustom];
  imageButton7.frame = CGRectMake(238, 166, 53, 54);
  [textureView1ContentView addSubview:imageButton7];
  imageButton7.alpha = 1.0;
  imageButton7.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [imageButton7 setTitle:@"" forState:UIControlStateNormal];
  [imageButton7 setImage:[UIImage imageNamed:@"WantMenuViewController_Image_14.png"] forState:UIControlStateNormal];
  imageButton7.enabled = YES;
  [imageButton7 setTitleColor:[UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0] forState:UIControlStateNormal];
  [imageButton7 addTarget:self action:@selector(didTap_imageButton7:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  // ----------------------------;
  // UIButton -> imageButton8;
  // ----------------------------;
  
  UIButton *imageButton8 = [UIButton buttonWithType:UIButtonTypeCustom];
  imageButton8.frame = CGRectMake(38, 285, 53, 54);
  [textureView1ContentView addSubview:imageButton8];
  imageButton8.alpha = 1.0;
  imageButton8.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  [imageButton8 setTitle:@"" forState:UIControlStateNormal];
  [imageButton8 setImage:[UIImage imageNamed:@"WantMenuViewController_Image_15.png"] forState:UIControlStateNormal];
  imageButton8.enabled = YES;
  [imageButton8 setTitleColor:[UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1.0] forState:UIControlStateNormal];
  [imageButton8 addTarget:self action:@selector(didTap_imageButton8:forEvent:) forControlEvents:UIControlEventTouchUpInside];
  
  
  contentView.frame = self.view.bounds;
  [self.view addSubview:contentView];
  [contentView release];
}

- (void)viewDidUnload {
  [super viewDidUnload];
}

- (void)dealloc {
  [super dealloc];
}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationFade];
    [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleDefault animated:animated];
}


// ----------------
// Tab Bar
// ----------------

- (void)tabBar:(UITabBar *)tabBar didSelectItem:(UITabBarItem *)item {
  if (tabBar.tag == 1 && item.tag == 1) {;
    [self didTap_tabBarItem1];
  };
  if (tabBar.tag == 1 && item.tag == 3) {;
    [self didTap_tabBarItem3];
  };
  if (tabBar.tag == 1 && item.tag == 4) {;
    [self didTap_tabBarItem4];
  };
}


// ----------------
// Navigation Bar
// ----------------

- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
  return NO;
}

// ----------------
// Action
// ----------------

- (void)didTap_tabBarItem1 {
  TradeMenuViewController *controller = [[TradeMenuViewController alloc] init];
  [self.navigationController pushViewController:controller animated:YES];
  [controller release];
}
- (void)didTap_tabBarItem3 {
  ForSaleViewController *controller = [[ForSaleViewController alloc] init];
  [self.navigationController pushViewController:controller animated:YES];
  [controller release];
}
- (void)didTap_tabBarItem4 {
  AreatradesViewController *controller = [[AreatradesViewController alloc] init];
  [self.navigationController pushViewController:controller animated:YES];
  [controller release];
}
- (void)didTap_barButton1:(id)sender forEvent:(UIEvent *)event {
  UIAlertView *alertView = [[UIAlertView alloc] init];
  alertView.title = @"Want menu";
  alertView.message = @"";
  [alertView addButtonWithTitle:@"OK"];
  [alertView show];
  [alertView release];
}
- (void)didTap_lightInfoButton1:(id)sender forEvent:(UIEvent *)event {
  InfoViewController *controller = [[InfoViewController alloc] init];
  UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:controller];
  [navigationController setNavigationBarHidden:YES animated:NO];
  navigationController.modalTransitionStyle = UIModalTransitionStylePartialCurl;
  navigationController.modalPresentationStyle = UIModalPresentationFormSheet;
  [self presentModalViewController:navigationController animated:YES];
  [navigationController release];
  [controller release];
}
- (void)didTap_imageButton2:(id)sender forEvent:(UIEvent *)event {
  WantViewController *controller = [[WantViewController alloc] init];
  [self.navigationController pushViewController:controller animated:YES];
  [controller release];
}
- (void)didTap_imageButton3:(id)sender forEvent:(UIEvent *)event {
  UIAlertView *alertView = [[UIAlertView alloc] init];
  alertView.title = @"Demo only";
  alertView.message = @"";
  [alertView addButtonWithTitle:@"OK"];
  [alertView show];
  [alertView release];
}
- (void)didTap_imageButton4:(id)sender forEvent:(UIEvent *)event {
  UIAlertView *alertView = [[UIAlertView alloc] init];
  alertView.title = @"Demo only";
  alertView.message = @"";
  [alertView addButtonWithTitle:@"OK"];
  [alertView show];
  [alertView release];
}
- (void)didTap_imageButton5:(id)sender forEvent:(UIEvent *)event {
  UIAlertView *alertView = [[UIAlertView alloc] init];
  alertView.title = @"Demo only";
  alertView.message = @"";
  [alertView addButtonWithTitle:@"OK"];
  [alertView show];
  [alertView release];
}
- (void)didTap_imageButton6:(id)sender forEvent:(UIEvent *)event {
  MultiAddScreenViewController *controller = [[MultiAddScreenViewController alloc] init];
  [self.navigationController pushViewController:controller animated:YES];
  [controller release];
}
- (void)didTap_imageButton7:(id)sender forEvent:(UIEvent *)event {
  UIAlertView *alertView = [[UIAlertView alloc] init];
  alertView.title = @"Demo only";
  alertView.message = @"";
  [alertView addButtonWithTitle:@"OK"];
  [alertView show];
  [alertView release];
}
- (void)didTap_imageButton8:(id)sender forEvent:(UIEvent *)event {
  UIAlertView *alertView = [[UIAlertView alloc] init];
  alertView.title = @"Demo only";
  alertView.message = @"";
  [alertView addButtonWithTitle:@"OK"];
  [alertView show];
  [alertView release];
}




@end